NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

include $(AM_HOME)/Makefile
$(info inside am/makefile , SRCS = $(SRCS))
$(info inside am/makefile , AM_SRCS = $(AM_SRCS))
